#include "./LOGO.h"

START_PROGRAM
	MAKE turtleMoves = LIST[	//TODO leftmost item has bigger list than it should
		ARRAY{ WORD: "FORWARD", NUMBER : 100 },
			ARRAY{ WORD: "RIGHT", NUMBER : 90 },
			ARRAY{ WORD: "FORWARD", NUMBER : 100 },
			ARRAY{ WORD: "RIGHT", NUMBER : 90 },
			ARRAY{ WORD: "FORWARD", NUMBER : 100 },
			ARRAY{ WORD: "LEFT", NUMBER : 90 },
			ARRAY{ WORD: "FORWARD", NUMBER : 100 },
			ARRAY{ WORD: "LEFT", NUMBER : 100 }
	]
	CENTER
	SETPENCOLOR LIST[NUMBER:0, NUMBER : 0, NUMBER : 0]
	REPEAT 2 TIMES
	DO
		FOREACH turtleMoves DO
			SHOW ELEM
		END
	END
	CENTER
	PENUP
	RIGHT NUMBER : 90
	FORWARD NUMBER : 150
	REPEAT 360 TIMES DO
		FORWARD NUMBER : 2
		LEFT NUMBER : 1
	END
END_PROGRAM

